name: IINACT build

on:
  push:
    branches: [ "cn-7.1" ]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      release_version: ${{ env.RELEASE_VERSION }}
    env:
      RELEASE_VERSION: '0.0.0.0'
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Download Dalamud
      shell: pwsh
      run: |
        $dalamudPath = "$env:APPDATA\XIVLauncher\addon\Hooks\dev"
        New-Item -ItemType Directory -Force -Path $dalamudPath
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/ottercorp/dalamud-distrib/refs/heads/main/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip $dalamudPath
    - name: Build
      run: dotnet build -c release
    - name: Prepare Build Artifact
      shell: pwsh
      run: |
        Copy-Item "IINACT/bin/Release/win-x64/IINACT/latest.zip" -Destination "IINACT.zip"
        Expand-Archive -Force IINACT.zip Artifact
    - name: Upload IINACT
      uses: actions/upload-artifact@v4
      with:
        name: IINACT
        path: Artifact/*
    - name: Update repo.json if needed
      shell: pwsh
      run: |
        $repo = Get-Content 'repo.json' -raw | ConvertFrom-Json
        $build = Get-Content 'IINACT/bin/Release/win-x64/IINACT/IINACT.json' -raw | ConvertFrom-Json
        if ($repo.AssemblyVersion -eq $build.AssemblyVersion) {
          Exit
        }
        Write-Output "RELEASE_VERSION=$($build.AssemblyVersion)" >> $env:GITHUB_ENV
        $repo.AssemblyVersion = $repo.TestingAssemblyVersion = $build.AssemblyVersion
        $baseUrl = "https://meowrs.com/https://github.com/MeowZWR/IINACT/releases/download/v"
        $repo.DownloadLinkInstall = $baseUrl + $repo.AssemblyVersion + '/IINACT.zip'
        $repo.DownloadLinkTesting = $baseUrl + $repo.TestingAssemblyVersion + '/IINACT.zip'
        $repo.DownloadLinkUpdate = $repo.DownloadLinkInstall
        $repo | ConvertTo-Json | % { "[`n" + $_ + "`n]" } | Set-Content 'repo.json'
    - name: Create Release
      if: ${{ env.RELEASE_VERSION != '0.0.0.0' }}
      uses: softprops/action-gh-release@v1
      with:
        files: IINACT.zip
        name: IINACT ${{ env.RELEASE_VERSION }}
        tag_name: v${{ env.RELEASE_VERSION }}
        prerelease: true
        append_body: true
        body_path: .github/release-notices.md
        generate_release_notes: true
        fail_on_unmatched_files: true
    - name: Commit repo.json
      if: ${{ env.RELEASE_VERSION != '0.0.0.0' }}
      id: commit
      run: |
        git config --global user.name "Actions User"
        git config --global user.email "actions@github.com"
        git fetch origin cn-7.1
        git checkout cn-7.1
        git add repo.json
        git commit -m "[CI] updating repo.json for ${{ env.RELEASE_VERSION }}" || true
        git push origin cn-7.1   
    
  trigger_workflow:
    needs: build
    if: ${{ needs.build.outputs.release_version != '0.0.0.0' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in DalamudPlugin Repository
        run: |
          repo_owner="MeowZWR"
          repo_name="DalamudPlugin"
          event_type="request-update-run-action"
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.MEOWRSTRIGGER }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
